//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileUpload.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FileName { get; set; }
        public byte[] FileContent { get; set; }
        public string FileId { get; set; }
        public string FileExt { get; set; }
        public string FileDesc { get; set; }
        public byte[] UploadDate { get; set; }
    }
}
